# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledNegotiations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_moment', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_game_uid', models.CharField(max_length=255)),
                ('count_of_games', models.PositiveIntegerField()),
                ('left_rate', models.CharField(max_length=255)),
                ('right_rate', models.CharField(max_length=2)),
                ('is_active', models.BooleanField()),
                ('left_count_of_money', models.CharField(max_length=255)),
                ('right_count_of_money', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderForDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_winner', models.BooleanField(default=False)),
                ('left_rate', models.CharField(max_length=255)),
                ('right_rate', models.CharField(max_length=2)),
                ('rate_trent', models.CharField(max_length=2)),
                ('games_count', models.PositiveIntegerField()),
                ('team_size', models.PositiveIntegerField()),
                ('in_negotiations', models.BooleanField(default=False)),
                ('modificate_moment', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.Deals')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.Games')),
            ],
        ),
        migrations.CreateModel(
            name='TempDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_game_uid', models.CharField(max_length=255)),
                ('count_of_games', models.PositiveIntegerField()),
                ('left_rate', models.CharField(max_length=255)),
                ('right_rate', models.CharField(max_length=2)),
                ('is_active', models.BooleanField()),
                ('left_count_of_money', models.CharField(max_length=255)),
                ('right_count_of_money', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='temp_deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.TempDeals'),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancelednegotiations',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor', to='disputes.OrderForDeal'),
        ),
        migrations.AddField(
            model_name='cancelednegotiations',
            name='myself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myself', to='disputes.OrderForDeal'),
        ),
    ]
