# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_is_read'),
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdeals',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
