# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_tempdeals_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='namespace',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='orderfordeal',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disputes.Deals'),
        ),
        migrations.AlterField(
            model_name='orderfordeal',
            name='games_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderfordeal',
            name='team_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderfordeal',
            name='temp_deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disputes.TempDeals'),
        ),
    ]
