# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0003_auto_20160926_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdeals',
            name='count_of_games',
        ),
        migrations.RemoveField(
            model_name='tempdeals',
            name='left_count_of_money',
        ),
        migrations.RemoveField(
            model_name='tempdeals',
            name='left_rate',
        ),
        migrations.RemoveField(
            model_name='tempdeals',
            name='right_count_of_money',
        ),
        migrations.RemoveField(
            model_name='tempdeals',
            name='right_rate',
        ),
        migrations.AlterField(
            model_name='cancelednegotiations',
            name='create_moment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
