# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_auto_20161002_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfordeal',
            name='temp_deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='disputes.TempDeals'),
        ),
    ]
