# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0005_auto_20161002_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempdeals',
            name='steam_game_uid',
        ),
    ]
