# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0006_remove_tempdeals_steam_game_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_game_uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='deals',
            name='steam_game_uid',
        ),
        migrations.AddField(
            model_name='steamgame',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disputes.Deals'),
        ),
    ]
