# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0007_auto_20161004_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfordeal',
            name='left_rate',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='rate_trent',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='right_rate',
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='fractional_part_from',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='fractional_part_to',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='integer_part_from',
            field=models.CharField(default='100', max_length=255),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='integer_part_to',
            field=models.CharField(default='1000', max_length=255),
        ),
    ]
