# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0008_auto_20161006_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelednegotiations',
            name='create_moment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
