# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disputes', '0009_auto_20161007_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='deals',
            name='count_of_games',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='left_count_of_money',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='left_rate',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='right_count_of_money',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='right_rate',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='user',
        ),
        migrations.AddField(
            model_name='games',
            name='appid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='disputes.OrderForDeal'),
        ),
        migrations.AddField(
            model_name='participants',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
