# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0010_auto_20161015_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='appid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
