# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0012_orderfordeal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderfordeal',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_sides', to='disputes.Deals'),
        ),
        migrations.AlterField(
            model_name='steamgame',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='disputes.Deals'),
        ),
    ]
