# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0013_auto_20161102_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfordeal',
            name='fractional_part_from',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='fractional_part_to',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='integer_part_from',
        ),
        migrations.RemoveField(
            model_name='orderfordeal',
            name='integer_part_to',
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='rate_left',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='orderfordeal',
            name='rate_right',
            field=models.IntegerField(default=100000),
        ),
    ]
