# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0015_auto_20161107_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdeals',
            name='chat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
    ]
