# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0017_deals_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='is_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deals',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
