# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0018_auto_20161130_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
