# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='is_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
