# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalname',
            name='dispute_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
