# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluuid',
            name='uid_for_client',
        ),
        migrations.AddField(
            model_name='additionaluuid',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='additionaluuid',
            name='series',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='additionaluuid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uid_for_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
