# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0002_auto_20160827_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluuid',
            name='uid_for_client',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
