# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_additionaluuid_uid_for_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluuid',
            old_name='uid_for_client',
            new_name='name',
        ),
    ]
