# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0005_userbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='fractional_part',
        ),
        migrations.RemoveField(
            model_name='userbalance',
            name='integer_part',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='balance',
            field=models.IntegerField(default=40000),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='frozen_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='withdrawn_balance',
            field=models.IntegerField(default=0),
        ),
    ]
